@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana{

object Game
object Player
object Board
object Snake
object Food


Game --* Player
Game --* Board
Player "1" -- "1" Snake
Board --* Food



}


@enduml